service: Crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'Dev'}

functions:
  User:
    handler: handlers/user.createUser
    events:
      - httpApi:
          path: user
          method: POST
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
