service: serverlesscrud
frameworkVersion: "3"

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002
    albPort: 4003

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'Dev'}

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /user
          method: POST

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
