service: Crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  User:
    handler: controller/user.createUser
    events:
      - httpApi:
          path: user
          method: POST
          cors: true

  getAllUser:
    handler: controller/user.getAllUser
    events:
      - httpApi:
          path: user
          method: GET
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
