service: serverlessCrud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /user
          method: POST

plugins:
  - serverless-offline
